version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - yum install -y zip

  pre_build:
    commands:
      - echo "Running pre-build phase (optional)..."
      
  build:
   commands:
    - echo "Installing project dependencies..."
    - npm install
    - echo "Building project..."
    - npm run build

post_build:
  commands:
    - echo "Zipping the build folder..."
    - zip -r output.zip build/
    - aws s3 cp output.zip s3://codepipeline-us-east-1-914035cea9d7-4ba5-a21c-f1c50f914996/output/output.zip --sse aws:kms

artifacts:
  files:
    - output.zip
